### ISSUE TITLE
Releases with a v infront aren't considered semvar

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/appcenter-dashboard#60]
https://github.com/ChildishGiant/mixer/releases/tag/v0.1.3 
`Latest release is not SemVer`
![image](https://user-images.githubusercontent.com/13716824/128546851-51cb427a-b1c8-499c-84b0-d26e151d9647.png)

**Comment by dar5hak** [comment]
Somewhat related: `docker-compose up` prints this error on my machine:

```
dashboard_1  | [error] GenServer #PID<0.592.0> terminating
dashboard_1  | ** (Version.InvalidVersionError) invalid version: "v0.0.16"
dashboard_1  |     (elixir 1.12.2) lib/version.ex:389: Version.parse!/1
dashboard_1  |     (appcenter_dashboard 0.1.0) lib/appcenter_dashboard/repository.ex:86: Elementary.AppcenterDashboard.Repository.parse_file!/1
dashboard_1  |     (elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2
dashboard_1  |     (appcenter_dashboard 0.1.0) lib/appcenter_dashboard/repository.ex:43: Elementary.AppcenterDashboard.Repository.handle_info/2
dashboard_1  |     (stdlib 3.15.2) gen_server.erl:695: :gen_server.try_dispatch/4
dashboard_1  |     (stdlib 3.15.2) gen_server.erl:771: :gen_server.handle_msg/6
dashboard_1  |     (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
dashboard_1  | Last message: :refresh
dashboard_1  | State: %{opts: [], releases: []}
dashboard_1  | [info] Application appcenter_dashboard exited: shutdown
```

I'm making a basic PR that should fix this; let me know if there's a better way.
